# -*- coding: utf-8 -*-
from odoo import fields, models


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    # Sin `copy=`: es copiable (default True), como `is_delivery` del core (molde correcto, ver
    # D33 de la spec). Con `copy=False` un pedido duplicado quedaria con la linea a $0 SIN el
    # flag: el primer recompute la llevaria a precio de tarifa y el sync crearia una segunda linea
    # gratis.
    is_free_battery_line = fields.Boolean(
        string="Is a Free Battery Line",
        default=False,
        help="Technical flag marking the lines generated by the free battery configuration, so "
             "they can be removed without guessing by product.",
    )

    def _is_installation_booking_line(self):
        """ Whether this line is the installation booked from the checkout.

        :rtype: bool
        """
        self.ensure_one()
        appointment_type = self.order_id.carrier_id.installation_appointment_type_id
        if not appointment_type:
            return False
        line_types = self.calendar_booking_ids.appointment_type_id | self.calendar_event_id.appointment_type_id
        return appointment_type in line_types

    def _timesheet_create_task_prepare_values(self, project):
        """ Override of `sale_project`: give the installation task a stable title.

        The line name of a booking is the booking description (appointment type + dates), and
        `sale_project` drops its first line when it matches the product name, leaving the task
        titled with the dates only. The crew reads this title on the Field Service board, so we
        keep it predictable: "<order> - <appointment type>".
        """
        values = super()._timesheet_create_task_prepare_values(project)
        if self._is_installation_booking_line():
            appointment_type = self.order_id.carrier_id.installation_appointment_type_id
            values["name"] = "%s - %s" % (self.order_id.name or "", appointment_type.name)
        return values

    # === FREE BATTERIES: PRICE / EDITION DEFENSES === #

    def _get_display_price(self):
        # LA garantia del precio 0 (D22): cubre tanto el recompute normal (_compute_price_unit
        # depende de product_id/product_uom_id/product_uom_qty, y esta linea cambia de cantidad
        # seguido) como el camino forzado (force_price_recomputation), que tambien termina aca
        # via _reset_price_unit(). Crear con price_unit=0 no alcanza: _add_precomputed_values
        # copia price_unit a technical_price_unit y has_manual_price da False.
        if self.is_free_battery_line:
            return 0.0
        return super()._get_display_price()

    def _compute_pricelist_item_id(self):
        # Que la linea gratis no arrastre descuento (D23): sin esto, una tarifa "percentage"
        # dejaria discount > 0 (prende la columna Descuento del PDF y el precio tachado en el
        # carrito). Molde literal: delivery._compute_pricelist_item_id (lineas de envio).
        free_lines = self.filtered("is_free_battery_line")
        super(SaleOrderLine, self - free_lines)._compute_pricelist_item_id()
        free_lines.pricelist_item_id = False

    def _check_validity(self):
        # Defensa en profundidad contra prevent_zero_price_sale: en el camino normal no se llama
        # (la linea se crea con sudo().create(), fuera de _cart_add/_cart_update_line_quantity),
        # pero /shop/cart/update con el line_id real SI pasa por aca, y el UserError del core
        # abortaria el request antes de que la re-sincronizacion pueda auto-curar (D21).
        if self.is_free_battery_line:
            return
        return super()._check_validity()

    def _is_reorder_allowed(self):
        # "Volver a pedir" no debe re-agregar la pila (D25): el filtro del core solo excluye
        # is_delivery/display_type/combo_item_id, asi que la linea gratis pasaria y se
        # re-agregaria sin el flag y a precio de tarifa.
        return super()._is_reorder_allowed() and not self.is_free_battery_line

    def _is_sellable(self):
        # La linea se ve pero no es editable ni clickeable (D20), con independencia de si el
        # producto de pila esta publicado (D29): sin este override, publicar la pila volveria a
        # habilitar el selector de cantidad por accidente de configuracion.
        return super()._is_sellable() and not self.is_free_battery_line

    def _check_availability(self):
        # Override de website_sale_stock (D34, no esta en depends: gana el MRO por orden de
        # carga). Sin esto, una pila storable sin "Sell when Out-of-Stock" y stock 0 (la
        # configuracion real de tmpl 411) dejaria al cliente sin poder pagar por un producto que
        # no eligio y que no puede eliminar (la auto-curacion lo repone).
        if self.is_free_battery_line:
            return True
        return super()._check_availability()

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
