# -*- coding: utf-8 -*-
from odoo import fields, models


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    is_payment_method_discount = fields.Boolean(
        string="Is a Payment Method Discount",
        default=False,
        copy=False,
        help="Technical flag marking the lines generated by the payment method price rule,"
             " so they can be removed without guessing by product.",
    )

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
